### ISSUE TITLE
Dose it work with Limesdr mini ?

### ISSUE THREAD

**Issue by XiaoliChan** [Synacktiv-contrib/Modmobjam#1]
Dose it work with Limesdr mini ? Did anyone test with Limesdr mini already ?

**Comment by FlUxIuS** [comment]
Hi,

It was tested with the classical LimeSDR USB Type-A and the LimeSuite Sink. So if you generate a new Python script with GNUradio Companion using the appropriate sink, this would work like a charm!

**Comment by XiaoliChan** [comment]
> Hi,
> 
> It was tested with the classical LimeSDR USB Type-A and the LimeSuite Sink. So if you generate a new Python script with GNUradio Companion using the appropriate sink, this would work like a charm!

I see, did you test auto attack script with limesdr?

**Comment by FlUxIuS** [comment]
The auto-attack script just take results from Modmodmap and send them to the XML-RPC server of the generated `GRC/jammer_gen.py`, that initially is the only thing to modify on the GRC schema.
We can provide a schema, and/or generated Python file, for each specific device that is not a problem. But I think, to do it in the cleaner way, we could also do lets say a `Device()` class that will support a lot of devices and select the one you need before lunching the server :)
