### ISSUE TITLE
Can Not Jamming ? Why ?

### ISSUE THREAD

**Issue by muratoznn** [Synacktiv-contrib/Modmobjam#4]
Aplications write this 

[+] Jamming cell 0x8ed2c6-9788 central frequency at 1957.6 MHz with 10 MHz bandwidth

but no jamming  Why ? 
İt is running but phone is connecting to this band perfectly ?

**Comment by FlUxIuS** [comment]
Hi,

Did you changed the sink?

Have you tried to amplify the different gain? Do you have by chance a receiver to observe if the noise is correctly transmitted?

Thanks in advance!

**Comment by muratoznn** [comment]
First I Added osmocom-sink After I added noise source like your jammer.grc  . I set up 80 gain all.I send noise to 2412 wifi frequency my wifi other wireless devices are disconnecting.  in my phone service mode 1450 earfcn I see. I calculated 1830 download link and I set up 1830 central frequency 20 mhz bandwitch . I send noise but phone not affecting. Why I dont understand ? Wifi is stopping when I send noise but mobile phone dont stop ? İt is effective about wifi devices but cell phone can not jamming : S I dont understand it ?

**Comment by FlUxIuS** [comment]
Yeah actually LTE is bit more tricky to jam, because as your can see you do not cover much bandwidth with your device. The EARFCN 1450 refers to a band 3 signal with a UL/DL 75 MHz bandwith in FDD LTE. If you have only one transmitter, try to launch the "smartjam_rpcclient.py" with 4 different frequencies to cover the whole bandwith of the DL link, on look at the service mode to see if the device hops to another cell.

**Comment by muratoznn** [comment]
Okay I tried it I tried 3 signal to cover 75 mhz bandwitch but no affect my mobile phone again ? I tried 1830 with 30 mhz bandwitch after 1845 mhz with 30 mhz bandwitch after 1860 mhz with 30 mhz bandwitch . It is working like this 1830 central frequency 1845 central frequency 1860 central frequency . İt is turning  like this but no affecting my mobile phone : S  I dont understand : S Is there something wrong with the wavelength?

**Comment by muratoznn** [comment]
I couldn't get out of this. Please help to me ? I dont understand .
I am attacking four different frequency now but my mobile phone dont affect a bit of : S
Why would that be? Can you understand?
proxy.set_centerfreq(1815e6)
time.sleep(1)
proxy.set_centerfreq(1830e6)
time.sleep(1)
proxy.set_centerfreq(1845e6)
time.sleep(1)
proxy.set_centerfreq(1860e6)
time.sleep(1)

**Comment by FlUxIuS** [comment]
As I cannot have the end of your setup, so I don't know actually if it is a problem of low noise sampling rate, hopping race, or the fact that actually the antenna signal is strong enough so the OFDM is on an acceptable level of noise. 

Did you tried making a call while jamming to see if there is an impact?

For technologies like 4G and 5G there better and smarter ways like playing with capabilities, as a jamming takes lot of resources here.

**Comment by oscarmh** [comment]
Hi, I use kalibrate with the HackRF, which will be the minimum JSON file for making modmobjam work ? Thanks in advance

**Comment by muratoznn** [comment]
İt is so strange . I existed a Limesdr sink (TX)  and connected to noise source. I tried al of sample rate to jamming 2G GSM arfcn 518 download link is 1806.4 MHz. But no do anything . I tried to wifi frequencies 2412 2442 2462 İt disconnected all of wireless device.  İt can be jamming all wireless devices but İt has no effect to cell phones . I dont understand . I wonder.  Are base stations using a different frequency from arfcn download link and upload link ?

**Comment by FlUxIuS** [comment]
> Hi, I use kalibrate with the HackRF, which will be the minimum JSON file for making modmobjam work ? Thanks in advance

Kalibrate does not provides a lot of information, use airprobe or grgsm_scanner that use the gr-gsm module instead. I will provide other modules for SDR as well as for modem in few weeks also.

**Comment by FlUxIuS** [comment]
> İt is so strange . I existed a Limesdr sink (TX) and connected to noise source. I tried al of sample rate to jamming 2G GSM arfcn 518 download link is 1806.4 MHz. But no do anything . I tried to wifi frequencies 2412 2442 2462 İt disconnected all of wireless device. İt can be jamming all wireless devices but İt has no effect to cell phones . I dont understand . I wonder. Are base stations using a different frequency from arfcn download link and upload link ?

Okay maybe I had to ask what SDR you are using, because I though you were using the hackRF. LimeSDR needs to now which port you want to use, and I guess it uses the port for above the 2GHz frequencies, especially if it's a LimeSDR mini. See: https://wiki.myriadrf.org/LimeSDR_Hardware_Installation#LimeSDR_Mini_RF_Ports

**Comment by VVaReD** [comment]
a version for hackrf please :-(

**Comment by muratoznn** [comment]
Yes İt is Limesdr Mini . But I set up high tx gain . İt is jamming all of wireless device but can not effect about cell phone. How I can fix this ? I am trying to jam phone İt is no effect . Should I use with low port frequency for it ?

**Comment by FlUxIuS** [comment]
Yes you should use the TX1_2 port for range 10MHz - 2GHz.
