### ISSUE TITLE
Problem Please Help ?

### ISSUE THREAD

**Issue by muratoznn** [Synacktiv-contrib/Modmobjam#5]
I am trying modmobjam with hackrf one now . I am attacking to uarfcn 10738 1 second uarfcn 10766 1 second 10763. But Mobile phone is changing its uarfcn with same time : ) . İt can not be jamming . I set up my phone only 3g umts . I found 3G base stations in my place. But cant jamming with modmobjam . Phone is catching with changing uarfcn.I am trying with Samsung M10 . How can solve this ?

**Comment by muratoznn** [comment]
Can I Use Osmo-fl2k for jamming tests ?

**Comment by muratoznn** [comment]
Modmobjam can not jamming mobile phones I tried a lot but if you send noise some time with a frequency it can be jamming. Signals can not jamming with 1 second noise source.

**Comment by FlUxIuS** [comment]
> I am trying modmobjam with hackrf one now . I am attacking to uarfcn 10738 1 second uarfcn 10766 1 second 10763. But Mobile phone is changing its uarfcn with same time : ) . İt can not be jamming . I set up my phone only 3g umts . I found 3G base stations in my place. But cant jamming with modmobjam . Phone is catching with changing uarfcn.I am trying with Samsung M10 . How can solve this ?

Seems like you finally succeeded in jamming some frequencies. The strategy is yours to find the right delays, or deploy more transceiver depending on the numbers of cell towers around. Be also aware of the noise amplitude that can vary depending on cell towers' closeness.

**Comment by muratoznn** [comment]
Modmobjammer problem is this. One cell tower can not jamming only 1 second noise source. But İf you make noise 6 7 second phone is stopping to transmit. For example I am attacking to my phone now . I found all of cell towers download frequencies. But modmobjamming dont affect to phone. I started to my sdr device and it changing frequency about 2 second . But phone do not affecting. How can we solve this problem ? Can we jamming onlu one sdr cell towers ? Look at this picture if I am starting lime sdr blackrf and limesdr mini . They are stopping cell signal connection. But how we do this jamming only one sdr ?  Or . Can we jamming only one sdr ?

**Comment by muratoznn** [comment]
![2020-02-04 01-14-19 ekran görüntüsü](https://user-images.githubusercontent.com/44745617/73696075-7eb15b00-46ec-11ea-8390-724810f79bf0.png)

**Comment by FlUxIuS** [comment]
> Modmobjammer problem is this. One cell tower can not jamming only 1 second noise source. But İf you make noise 6 7 second phone is stopping to transmit. For example I am attacking to my phone now . I found all of cell towers download frequencies. But modmobjamming dont affect to phone. I started to my sdr device and it changing frequency about 2 second . But phone do not affecting. How can we solve this problem ? Can we jamming onlu one sdr cell towers ? Look at this picture if I am starting lime sdr blackrf and limesdr mini . They are stopping cell signal connection. But how we do this jamming only one sdr ? Or . Can we jamming only one sdr ?

Hi,

You may change the delay to any order that allows you to make the cell phone change frequencies. Generally, if you can send enough noise in a short period of time, you'll have more chances to jam multiple channels => it is a race
The more you'll have transmitters the more efficient the attack will be. But the attack with 1 SDR on 4 channels worked for 4 cells and demonstrated in this video: https://penthertz.com/resources/Demo_NDH2k16-Jamming_3G.webm
Look by decreasing the delay < 1s, or look on the hopping strategy used by the phone. In the Nexus 6 case, the phone tried to change frequencies for few seconds and then kept using GSM for an hour, even passing from fly mode => I had to reboot it. But all basebands behave differently.
