### ISSUE TITLE
grgsm_scanner output and minimal json file 

### ISSUE THREAD

**Issue by oscarmh** [Synacktiv-contrib/Modmobjam#6]
Hi there !! as you suggested 

![grgsmscannercapture](https://user-images.githubusercontent.com/17768352/82077753-3f79a980-96e0-11ea-98fe-f6c109146d5a.png)

will you please be so kind to let me know which will be the minimum json I must compose to make modmobjam work ? thanks in advace

**Comment by FlUxIuS** [comment]
Sure I just uploaded few samples to https://github.com/PentHertz/Modmobmap/tree/master/samples

**Comment by FlUxIuS** [comment]
> Sure I just uploaded few samples to https://github.com/PentHertz/Modmobmap/tree/master/samples

@oscarmh please also find a new feature in Modmobmap that allows you too directly record information from GRGSM's scanner: https://github.com/PentHertz/Modmobmap#using-modmobmap-with-grgsm

Can you test it to see if everything works as expected?

Thanks in advance!

Cheers,
Seb
