### ISSUE TITLE
Modmobjam for supporting GSM

### ISSUE THREAD

**Issue by Dastgsm** [Synacktiv-contrib/Modmobjam#8]
is the modmobjam support gsm jamming or just 3G and 4G ? How to process if I want make a gsm jamming with modmobjam?

Chears,

**Comment by FlUxIuS** [comment]
Hi,

First use the https://github.com/PentHertz/Modmobjam repo, has this one is obsolete. 

About your question, you can use Modmobjam to Jam frequencies you reference in a json file. This JSON file can be generated with https://github.com/PentHertz/Modmobmap, or generated with a custom tool.

Here is a sample of a file:
```
{
    "346-1501": {
        "PCI": "346", 
        "PLMN": "208-10", 
        "TAC": "58104", 
        "band": 3, 
        "bandwidth": "20MHz_", 
        "eARFCN": 1501, 
        "type": "4G"
    }
}
```

The important parameters are the (e/u)ARFCN and the bandwidth.
